#%RAML 1.0 DataType
type: object
properties:  
  systemName:
    description: Name of the system of the backend system
    type: string
  connectionConfig:
    required: false
    description: Connection configuration of the backend system, no password
    type: string
  status:
    description: Health status of backend system (OK = good, ERROR =underlying system fails, UNKNOWN = typo on a flow name)   
    type: 
    enum:
      - OK
      - ERROR
      - UNKNOWN
  
  exception:
    type: string
    description: Summary message of exception that occured during any system call

  timestamp:
    description: Current timestamp in yyyy-MM-dd HH:mm:ss format
    type: string