#%RAML 1.0 DataType

uses:
  jvm: jvm-info.raml

type: object
properties:
  request:
    type: !include request-info.raml
    description: Health check request information
  mule:
    type: !include mule-info.raml
    description: Mule runtime information
  server:
    type: !include server-info.raml
    description: Server and OS information
  git:
    required: false
    type: !include git-info.raml
    description: Git information for this build
  build:
    required: false
    type: !include build-info.raml
    description: Build information (artifact name, version and groupid)
  jvm:
    type: jvm.jvm
    description: JVM information including version, memory, gc and thread usage
  systems:
    type: array
    items: !include system-check.raml
    description: List of system health check results