#%RAML 1.0 DataType
type: object
description: 
properties:
  init: 
    type: number
    description: 
    example: 264241152
  used:
    type: number
    description: The mule runtime version the application is running on
    example: 382810496
  committed:
    type: number
    description: The mule runtime version the application is running on
    example: 1030225920
  max:
    type: number
    description: The mule runtime version the application is running on
    example: 3756523520