#%RAML 1.0 NamedExample
{
  "request" : {
    "timestamp": "2019-12-27T11:23:18.168-06:00",
    "correlationId": "925bfc10-28cd-11ea-b774-105bad3268d7",
    "url": "http://localhost:8081/lib/health/check",
    "status": "OK"
  },  
  "mule" : {
    "appName" : "health-check-api-example",
    "runtimeVersion" : "4.2.2",
    "environment" : "DEV"
  },
  "server" : {
    "host" : "AC0050",
    "ip" : "10.0.0.1",
    "timeZone" : "Central Standard Time",
    "osName": "Linux",
    "osVersion": "5.3.0-45-generic",
    "osArchitecture": "amd64",
    "systemLoadAverage": 1.27,
    "availableProcessors": 12,
    "freePhysicalMemorySize": 3750350848,
    "processCpuTime": 14437500000,
    "systemCpuLoad": 0.0,
    "processCpuLoad": 0.05657935521623634    
  },
  "git" : {
    "commit" : {
      "time" : "2019-12-27T11:23:18.168-06:00",
      "id" : "df027cf"
    },
    "branch" : "master"
  },
  "build" : {
    "version" : "1.0.3",
    "artifact" : "health-check-api-example",
    "group" : "com.avioconsulting.mule.api"
  },
  "jvm": {
    "vmName": "Java HotSpot(TM) 64-Bit Server VM",
    "vmVendor": "Oracle Corporation",
    "vmVersion": "1.8.0_231",
    "pid": "29488@AC0084",
    "locale": "English (United States)",
    "memory": {
      "heap": {
        "init": 264241152,
        "used": 212208352,
        "committed": 513802240,
        "max": 3756523520
      },
      "nonHeap": {
        "init": 2555904,
        "used": 61171016,
        "committed": 62193664,
        "max": -1
      }
    },
    "threadCount": {
      "activeThreadCount": 54,
      "daemonThreadCount": 48
    },
    "garbageCollection": [
      {
        "gcName": "PS Scavenge",
        "collectionCount": 8,
        "collectionTime": 67
      },
      {
        "gcName": "PS MarkSweep",
        "collectionCount": 2,
        "collectionTime": 221
      }
    ]
  },
  "systems" : [  
      {
        "name": "HTTPS",
        "connectionConfig": "api-dev.srs.aws.avioconsulting.com:443/orders-system-api",
        "user": "N/A",
        "status": "OK",
        "exception": "N/A",
        "timestamp": "2019-12-27T11:23:18.168-06:00",
        "executionTime" : 10.7
      },
      {
        "name" : "Amazon S3",
        "connectionConfig" : "N/A",
        "user": "N/A",
        "status" : "ERROR",
        "exception": "N/A",
        "timestamp": "2019-12-27T11:23:18.168-06:00",
        "executionTime" : 10.7
      },
      {
        "name": "SQLServer",
        "connectionConfig": "jdbc:sqlserver://localhost;ODSAPI;ODSApiApp",
        "user": "sql-user",
        "status": "OK",
        "exception": "",
        "timestamp": "2019-12-27T11:23:18.168-06:00",
        "executionTime" : 10.7
      }
  ]   
}