#%RAML 1.0 NamedExample
{
  "muleProperties": {
    "muleRuntime": "3.9.3",
    "apiName": "health-check-api",
    "server": "AC0084",
    "url": "http://localhost:8081/lib/health/check",
    "ip": "10.0.75.1",
    "timeZone": "America/Chicago",
    "environment": "${env}"
  },
  "jvmProperties": {
    "pid": "29488@AC0084",
    "vmName": "Java HotSpot(TM) 64-Bit Server VM",
    "vmVendor": "Oracle Corporation",
    "vmVersion": "1.8.0_231",
    "locale": "English (United States)",
    "memory": {
      "heapMemoryUsage": {
        "init": 264241152,
        "used": 212208352,
        "committed": 513802240,
        "max": 3756523520
      },
      "nonHeapMemoryUsage": {
        "init": 2555904,
        "used": 61171016,
        "committed": 62193664,
        "max": -1
      }
    },
    "threadCount": {
      "activeThreadCount": 54,
      "daemonThreadCount": 48
    },
    "garbageCollection": [
      {
        "gcName": "PS Scavenge",
        "collectionCount": 8,
        "collectionTime": 67
      },
      {
        "gcName": "PS MarkSweep",
        "collectionCount": 2,
        "collectionTime": 221
      }
    ]
  },
  "osProperties": {
    "osName": "Windows 10",
    "osVersion": "10.0",
    "osArchitechture": "amd64",
    "systemLoadAverage": -1.0,
    "availableProcessors": 12,
    "freePhysicalMemorySize": 3750350848,
    "processCpuTime": 14437500000,
    "systemCpuLoad": 0.0,
    "processCpuLoad": 0.05657935521623634
  },
  "timestamp": "2019-12-27T11:23:18.168-06:00",
  "correlationId": "925bfc10-28cd-11ea-b774-105bad3268d7"
}