name: Maven build and release for mule-health-check-api

on:
  push:
    branches:
      - 'main'
      - 'chore/**'
      - 'feat/**'
  pull_request:
    branches:
      - 'main'

jobs:
  Build-Maven:
    uses: avioconsulting/shared-workflows/.github/workflows/maven-build.yml@main
    with:
      include-mule-ee-repo: true

  Release-Maven:
    needs: Build-Maven
    uses: avioconsulting/shared-workflows/.github/workflows/maven-release.yml@main
    with:
      app-version: ${{ needs.Build-Maven.outputs.app-version }}
      publish-maven-central: true

  Post-Release-Maven:
    needs: [Build-Maven, Release-Maven]
    uses: avioconsulting/shared-workflows/.github/workflows/maven-post-release.yml@main
    with:
      app-version: ${{ needs.Build-Maven.outputs.app-version }}